namespace SESM.DTO
{
    public enum EnumHostPerm : int
    {
        // 000+ : Misc
        MISC_CRON = 1,

        // 100+ : Server
        SERVER_CREATE = 101,

        // 200+ : Host Access
        ACCESS_HOST_READ = 200,
        ACCESS_HOST_CREATE = 201,
        ACCESS_HOST_DELETE = 202,
        ACCESS_HOST_EDIT_NAME = 203,
        ACCESS_HOST_EDIT_PERMISSION = 204,
        ACCESS_HOST_EDIT_USERS = 205,

        // 300+ : Server Access
        ACCESS_SERVER_READ = 300,
        ACCESS_SERVER_CREATE = 301,
        ACCESS_SERVER_DELETE = 302,
        ACCESS_SERVER_EDIT_NAME = 303,
        ACCESS_SERVER_EDIT_PERMISSION = 304,
        ACCESS_SERVER_EDIT_USERS = 305,

        // 400+ : Perf Monitor
        PERF_CLEANUP = 400,

        // 500+ : Setting
        SETTINGS_SESM = 500,
        SETTINGS_SE = 510,
        SETTINGS_SESE = 520,
        SETTINGS_ME = 530,

        // 600+ : User Manager
        USER_MANAGE = 600,

        // 1000+ : Global Server
        SERVER_INFO = 1000,
        SERVER_DELETE = 1001,


        // 1010+ : Server Power
        SERVER_START = 1011,
        SERVER_STOP = 1012,
        SERVER_RESTART = 1013,
        SERVER_KILL = 1014,

        // 1100+ : Server Settings
        // 1110+ : Server global Settings
        SERVER_SETTINGS_GLOBAL_RD = 1110,
        SERVER_SETTINGS_GLOBAL_NAME_WR = 1111,
        SERVER_SETTINGS_GLOBAL_USESESE_WR = 1112,
        SERVER_SETTINGS_GLOBAL_PROCESSPRIO_WR = 1113,
        SERVER_SETTINGS_GLOBAL_PUBLIC_WR = 1114,
        SERVER_SETTINGS_GLOBAL_STARTUPTYPE_WR = 1115,

        // 1120+ : Server jobs Settings
        SERVER_SETTINGS_JOBS_RD = 1120,
        SERVER_SETTINGS_JOBS_AUTORESTART_WR = 1121,
        SERVER_SETTINGS_JOBS_AUTORESTARTCRON_WR = 1122,
        SERVER_SETTINGS_JOBS_AUTOSTART_WR = 1123,

        // 1130+ : Server Backup Settings
        SERVER_SETTINGS_BACKUPS_RD = 1130,
        SERVER_SETTINGS_BACKUPS_LVL1_WR = 1131,
        SERVER_SETTINGS_BACKUPS_LVL2_WR = 1132,
        SERVER_SETTINGS_BACKUPS_LVL3_WR = 1133,

        // 1200+ : SE Server Configuration
        SERVER_CONFIG_SE_RD = 1200,
        SERVER_CONFIG_SE_IP_WR = 1201,
        SERVER_CONFIG_SE_STEAMPORT_WR = 1202,
        SERVER_CONFIG_SE_SERVERPORT_WR = 1203,
        SERVER_CONFIG_SE_SERVERNAME_WR = 1204,
        SERVER_CONFIG_SE_IGNORELASTSESSION_WR = 1205,
        SERVER_CONFIG_SE_PAUSEGAMEWHENEMPTY_WR = 1206,
        SERVER_CONFIG_SE_ENABLESPECTATOR_WR = 1207,
        SERVER_CONFIG_SE_REALISTICSOUND_WR = 1208,
        SERVER_CONFIG_SE_AUTOSAVEINMINUTES_WR = 1209,
        SERVER_CONFIG_SE_INVENTORYSIZEMULTIPLIER_WR = 1210,
        SERVER_CONFIG_SE_ASSEMBLERSPEEDMULTIPLIER_WR = 1211,
        SERVER_CONFIG_SE_ASSEMBLEREFFICIENCYMULTIPLIER_WR = 1212,
        SERVER_CONFIG_SE_REFINERYSPEEDMULTIPLIER_WR = 1213,
        SERVER_CONFIG_SE_GAMEMODE_WR = 1214,
        SERVER_CONFIG_SE_ENABLECOPYPASTE_WR = 1215,
        SERVER_CONFIG_SE_WELDERSPEEDMULTIPLIER_WR = 1216,
        SERVER_CONFIG_SE_GRINDERSPEEDMULTIPLIER_WR = 1217,
        SERVER_CONFIG_SE_HACKSPEEDMULTIPLIER_WR = 1218,
        SERVER_CONFIG_SE_DESTRUCTIBLEBLOCKS_WR = 1219,
        SERVER_CONFIG_SE_MAXPLAYERS_WR = 1220,
        SERVER_CONFIG_SE_MAXFLOATINGOBJECTS_WR = 1221,
        SERVER_CONFIG_SE_WORLDNAME_WR = 1222,
        SERVER_CONFIG_SE_ENVIRONMENTHOSTILITY_WR = 1223,
        SERVER_CONFIG_SE_WORLDSIZEKM_WR = 1224,
        SERVER_CONFIG_SE_PERMANENTDEATH_WR = 1225,
        SERVER_CONFIG_SE_CARGOSHIPSENABLED_WR = 1226,
        SERVER_CONFIG_SE_REMOVETRASH_WR = 1227,
        SERVER_CONFIG_SE_CLIENTCANSAVE_WR = 1228,
        SERVER_CONFIG_SE_MODS_WR = 1229,
        SERVER_CONFIG_SE_VIEWDISTANCE_WR = 1230,
        SERVER_CONFIG_SE_ONLINEMODE_WR = 1231,
        SERVER_CONFIG_SE_RESETOWNERSHIP_WR = 1232,
        SERVER_CONFIG_SE_GROUPID_WR = 1233,
        SERVER_CONFIG_SE_ADMINISTRATORS_WR = 1234,
        SERVER_CONFIG_SE_BANNED_WR = 1235,
        SERVER_CONFIG_SE_AUTOHEALING_WR = 1236,
        SERVER_CONFIG_SE_WEAPONSENABLED_WR = 1237,
        SERVER_CONFIG_SE_SHOWPLAYERNAMESONHUD_WR = 1238,
        SERVER_CONFIG_SE_THRUSTERDAMAGE_WR = 1239,
        SERVER_CONFIG_SE_SPAWNSHIPTIMEMULTIPLIER_WR = 1240,
        SERVER_CONFIG_SE_RESPAWNSHIPDELETE_WR = 1241,
        SERVER_CONFIG_SE_ENABLETOOLSHAKE_WR = 1242,
        SERVER_CONFIG_SE_ENABLEINGAMESCRIPTS_WR = 1243,
        SERVER_CONFIG_SE_VOXELGENERATORVERSION_WR = 1244,
        SERVER_CONFIG_SE_ENABLEOXYGEN_WR = 1245,
        SERVER_CONFIG_SE_ENABLE3RDPERSONVIEW_WR = 1246,
        SERVER_CONFIG_SE_ENABLEENCOUNTERS_WR = 1247,
        SERVER_CONFIG_SE_ENABLEFLORA_WR = 1248,
        SERVER_CONFIG_SE_ENABLESTATIONVOXELSUPPORT_WR = 1249,
        SERVER_CONFIG_SE_ENABLESUNROTATION_WR = 1250,
        SERVER_CONFIG_SE_DISABLERESPAWNSHIPS_WR = 1251,
        SERVER_CONFIG_SE_SCENARIOEDITMODE_WR = 1252,
        SERVER_CONFIG_SE_BATTLE_WR = 1253,
        SERVER_CONFIG_SE_SCENARIO_WR = 1254,
        SERVER_CONFIG_SE_CANJOINRUNNING_WR = 1255,
        SERVER_CONFIG_SE_PHYSICSITERATIONS_WR = 1256,
        SERVER_CONFIG_SE_SUNROTATIONINTERVALMINUTES_WR = 1257,
        SERVER_CONFIG_SE_ENABLEJETPACK_WR = 1258,
        SERVER_CONFIG_SE_SPAWNWITHTOOLS_WR = 1259,
        SERVER_CONFIG_SE_STARTINRESPAWNSCREEN_WR = 1260,
        SERVER_CONFIG_SE_ENABLEVOXELDESTRUCTION_WR = 1261,
        SERVER_CONFIG_SE_MAXDRONES_WR = 1262,
        SERVER_CONFIG_SE_ENABLEDRONES_WR = 1263,
        SERVER_CONFIG_SE_FLORADENSITY_WR = 1264,
        SERVER_CONFIG_SE_ENABLECYBERHOUNDS_WR = 1265,
        SERVER_CONFIG_SE_ENABLESPIDERS_WR = 1266,
        SERVER_CONFIG_SE_FLORADENSITYMULTIPLIER_WR = 1267,

        // 1300+ : ME Server Configuration
        SERVER_CONFIG_ME_RD = 1300,
        SERVER_CONFIG_ME_IP_WR = 1301,
        SERVER_CONFIG_ME_STEAMPORT_WR = 1302,
        SERVER_CONFIG_ME_SERVERPORT_WR = 1303,
        SERVER_CONFIG_ME_SERVERNAME_WR = 1304,
        SERVER_CONFIG_ME_IGNORELASTSESSION_WR = 1305,
        SERVER_CONFIG_ME_PAUSEGAMEWHENEMPTY_WR = 1306,
        SERVER_CONFIG_ME_ENABLESPECTATOR_WR = 1307,
        SERVER_CONFIG_ME_AUTOSAVEINMINUTES_WR = 1308,
        SERVER_CONFIG_ME_GAMEMODE_WR = 1309,
        SERVER_CONFIG_ME_ENABLECOPYPASTE_WR = 1310,
        SERVER_CONFIG_ME_MAXPLAYERS_WR = 1311,
        SERVER_CONFIG_ME_WORLDNAME_WR = 1312,
        SERVER_CONFIG_ME_MODS_WR = 1313,
        SERVER_CONFIG_ME_ONLINEMODE_WR = 1314,
        SERVER_CONFIG_ME_GROUPID_WR = 1315,
        SERVER_CONFIG_ME_ADMINISTRATORS_WR = 1316,
        SERVER_CONFIG_ME_BANNED_WR = 1317,
        SERVER_CONFIG_ME_CLIENTCANSAVE_WR = 1318,
        SERVER_CONFIG_ME_ENABLESTRUCTURALSIMULATION_WR = 1319,
        SERVER_CONFIG_ME_MAXACTIVEFRACTUREPIECES_WR = 1320,
        SERVER_CONFIG_ME_ENABLEBARBARIANS_WR = 1321,
        SERVER_CONFIG_ME_MAXIMUMBOTS_WR = 1322,
        SERVER_CONFIG_ME_GAMEDAYINREALMINUTES_WR = 1323,
        SERVER_CONFIG_ME_DAYNIGHTRATIO_WR = 1324,
        SERVER_CONFIG_ME_ENABLEANIMALS_WR = 1325,

        // 1400+ : Server Explorer
        SERVER_EXPLORER_LIST = 1400,
        SERVER_EXPLORER_DELETE = 1401,
        SERVER_EXPLORER_RENAME = 1402,
        SERVER_EXPLORER_RENAMETODLL = 1403,
        SERVER_EXPLORER_DOWNLOAD = 1404,
        SERVER_EXPLORER_CREATE_FOLDER = 1405,
        SERVER_EXPLORER_CREATE_FILE = 1406,
        SERVER_EXPLORER_UPLOAD = 1407,
        SERVER_EXPLORER_UPLOADDLL = 1408,
        SERVER_EXPLORER_READFILE = 1409,
        SERVER_EXPLORER_WRITEFILE = 1410,

        // 1500+ : SE Map
        SERVER_MAP_SE_LIST = 1500,
        SERVER_MAP_SE_SELECT = 1501,
        SERVER_MAP_SE_DELETE = 1502,
        SERVER_MAP_SE_DOWNLOAD = 1503,
        SERVER_MAP_SE_CREATE = 1504,
        SERVER_MAP_SE_UPLOAD = 1505,

        // 1600+ : ME Map
        SERVER_MAP_ME_LIST = 1600,
        SERVER_MAP_ME_SELECT = 1601,
        SERVER_MAP_ME_DELETE = 1602,
        SERVER_MAP_ME_DOWNLOAD = 1603,
        SERVER_MAP_ME_CREATE = 1604,
        SERVER_MAP_ME_UPLOAD = 1605,

        // 1700+ : Perf Monitor
        SERVER_PERF_READ = 1700
    }
}