// <auto-generated />
namespace SESM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AutoRestart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoRestart));
        
        string IMigrationMetadata.Id
        {
            get { return "201408291553553_AutoRestart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
