// <auto-generated />
namespace SESM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SESEAutoSave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SESEAutoSave));
        
        string IMigrationMetadata.Id
        {
            get { return "201411152236535_SESEAutoSave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
